name: cronTest

on:
  schedule:
     - cron: '30 1 * * 1-5'
     - cron: '30 13 * * 1-5'


jobs:
  gitHubCronTest:
    # Name the Job
    name: Job name test
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
           distribution: 'zulu'
           java-version: '11'
           java-package: jdk
    - run: java -cp javaprintHello.java
