name: ManualTest

on:
  schedule:
     - cron: '30 1 * * 1-5'
     - cron: '30 13 * * 1-5'


jobs:
  gitHubActionsTest:
    # Name the Job
    name: Job name test
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    #https://github.com/marketplace?type=actions&query=java 
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-java@v1
          with:
                java-version: '11' 
                java-package: jdk 
                architecture: x64 
        - run: java -cp java printHello.java
