name: cronTest

on:
  schedule:
     - cron: '30 1 * * 1-5'
     - cron: '30 13 * * 1-5'


jobs:
  gitHubCronTest:
    # Name the Job
    name: Job name test
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    #https://github.com/marketplace?type=actions&query=java 
    steps:
             - name: Checkout code
               uses: actions/checkout@v2

             - name: Set up JDK
               uses: actions/setup-java@v2
               with:
                java-version: '11'
               
             - name: Run file
               run : java -cp java printHello.java
