name: cronTest

on:
  schedule:
     - cron: '30 4 * * 1-5'
     - cron: '30 16 * * 1-5'


jobs:
  test:
    # Name the Job
    name: Cron_test
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
           distribution: 'zulu'
           java-version: '11'
           java-package: jdk
    - run: java -cp javaprintHello.java
    
    - name: Build with Maven
      run: mvn clean test
