name: gitHubActionsTest

on: 
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  gitHubActionsTest:
    # Name the Job
    name: Job name test
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    #https://github.com/marketplace?type=actions&query=java 
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
         distribution: 'zulu'
         java-version: '11'
         java-package: jdk 
    - run: java -cp java printHello.java
