name: cronTest

on:
  workflow_dispatch:
  schedule:
   # - cron: '10 5 * * 1-5'
    # - cron: '10 17 * * 1-5'
     - cron: '32 5,17  * * *'
permissions:
  contents: read
jobs:
  test:
    # Name the Job
    name: Cron_test
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
           distribution: 'zulu'
           java-version: '11'
           java-package: jdk
    - run: java -cp java printHello.java
    
    - name: Build with Maven
      run: mvn clean test
