name: githubActionsWithPublishTestReport

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11' 
        
    - run: java -cp java printHello.java

    - name: Build with Maven
      run: mvn clean install  
      
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action/composite@v2
      if: always()
      with:
          files: |
            test-results/**/*.xml
