name: secretExistenceActionTest

on: 
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  existenceActionTest:
    name: Job name test
   
    runs-on: ubuntu-latest

  
    steps:    
    - name: Check file existence
      id: check_files
      uses: devsamuelv/secret-existence@v1
      with:
          files: "pom.xml, README.md"
